matrix:
  include:
    - language: python
      cache: pip
      python:
          - "3.8"
      # install dependencies
      install: "pip install -r requirements.txt"
      services:
          - postgresql
          - redis-server
      before_script:
        - pycodestyle
      #    - psql -c 'create database test_postgres;' -U postgres
      #    - python manage.py migrate
      #  - prospector
      script: python manage.py test --settings=hbapi.settings.travis
    - language: node_js
      cache:
        yarn: true
        directories:
          - reactapp/node_modules
      node_js:
        - "8.9.1"
      before_install:
        - export TZ=America/Vancouver
      before_script:
        - cd reactapp
      script:
        - npm test
