language: python
cache: pip
python:
    - "3.5"
# install dependencies
install: "pip install -r requirements.txt"
services: postgresql
#before_script:
#    - psql -c 'create database test_postgres;' -U postgres
#    - python manage.py migrate
script: python manage.py test --settings=hbapi.settings.travis

