version: "2"
services:
  db:
    image: "postgres"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  web:
    build: "."
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    links:
      - "db"

volumes:
  pg_data:
