version: '2'
services:
  db:
    image: postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pg_data:
