# Generated by Django 2.0.2 on 2018-08-18 23:11
import itertools

from django.db import migrations


def add_tags_to_user(apps, schema_editor):
    Record = apps.get_model('records', 'Record')
    User = apps.get_model('userprofile', 'User')
    users = User.objects.all()
    for user in users:
        all_tags = list(Record.objects.filter(user=user).values_list('tags', flat=True))
        unique_tags = list(set(itertools.chain(*all_tags)))
        user.tags = unique_tags
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_user_tags'),
    ]

    operations = [
        migrations.RunPython(add_tags_to_user),
    ]
