# Generated by Django 2.0.2 on 2018-12-08 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20), blank=True, default=[], size=None),
        ),
    ]
