# Generated by Django 3.0.3 on 2020-02-26 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20181207_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
