# Generated by Django 2.0.2 on 2020-02-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
