# Generated by Django 3.0.3 on 2020-02-26 16:11

import django.contrib.postgres.fields
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20181204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CAD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
