# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:02
from __future__ import unicode_literals

import bitfield.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20160708_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=bitfield.models.BitField((('books', 'Books'), ('cafe', 'Cafe'), ('clothes', 'Clothes'), ('fees', 'Fees'), ('food', 'Food'), ('fun', 'Fun'), ('gift', 'Gift'), ('health', 'Health'), ('hobby', 'Hobby'), ('household', 'Household'), ('hz', 'HZ'), ('internet', 'Internet'), ('lunch', 'Lunch'), ('managment_fee', 'Managment fee'), ('mobile', 'Mobile'), ('rent', 'Rent'), ('school', 'School'), ('sport', 'Sport'), ('tax', 'Tax'), ('technics', 'Technics'), ('to_save', 'To savings'), ('toys', 'Toys'), ('transport', 'Transport'), ('travel', 'Travel'), ('salary', 'Salary'), ('other', 'Other')), default=None, validators=[django.core.validators.MinValueValidator(1, message='Select any tag.')]),
        ),
    ]
