# Generated by Django 3.0.3 on 2020-02-25 20:54

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CAD', max_digits=15),
        ),
    ]
