# Generated by Django 2.0.2 on 2018-03-10 22:42

from django.db import migrations

TAGS = (
    ('books', 'Books'),
    ('cafe', 'Cafe'),
    ('clothes', 'Clothes'),
    ('fees', 'Fees'),
    ('food', 'Food'),
    ('fun', 'Fun'),
    ('gift', 'Gift'),
    ('health', 'Health'),
    ('hobby', 'Hobby'),
    ('household', 'Household'),
    ('hz', 'HZ'),
    ('internet', 'Internet'),
    ('lunch', 'Lunch'),
    ('managment_fee', 'Managment fee'),
    ('mobile', 'Mobile'),
    ('rent', 'Rent'),
    ('school', 'School'),
    ('sport', 'Sport'),
    ('tax', 'Tax'),
    ('technics', 'Technics'),
    ('to_save', 'To savings'),
    ('toys', 'Toys'),
    ('transport', 'Transport'),
    ('travel', 'Travel'),
    ('salary', 'Salary'),
    ('other', 'Other'),
)

def forward_func(apps, schema):
    Record = apps.get_model('records', 'Record')
    tags_names = dict(TAGS)
    for r in Record.objects.all():
        new_tags = []
        for tag in [tag for tag, val in r.tags.items() if val]:
            new_tags.append(tags_names[tag])
        r.record_tags = new_tags
        r.save()


def backward_func(apps, schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_record_tags'),
    ]

    operations = [
        migrations.RunPython(forward_func, backward_func)
    ]
