# Generated by Django 2.0.2 on 2018-03-11 03:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_fill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
