# Generated by Django 2.0.2 on 2018-03-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180310_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tags',
        ),
    ]
