# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='tags_type',
            field=models.CharField(choices=[('INCL', 'Tags Include'), ('EXCL', 'Tags Exclude')], max_length=4),
        ),
    ]
