# Generated by Django 2.0.2 on 2018-03-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20180310_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='record_tags',
            new_name='tags',
        ),
    ]
